# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - nightly
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pwd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/install_wkhtmltoimage.sh ; fi
notifications:
  email: true
script:
 - pwd
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - ls -a
 - julia -e 'using Pkg; Pkg.add(PackageSpec(url=pwd()))'
 - ls -a
 - julia -e 'using Pkg; Pkg.build("Plots")'
 - julia test/travis_commands.jl